version: '3.8'

services:
  app:
    image: php:8.2-fpm
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lara_ecommerce_api
    ports:
      - 3306:3306
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
