name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: lara_ecommerce_api
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Copy .env file
        run: cp .env.example .env

      - name: Update .env for testing
        run: |
          sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=mysql/' .env
          sed -i 's/DB_HOST=127.0.0.1/DB_HOST=127.0.0.1/' .env
          sed -i 's/DB_PORT=3306/DB_PORT=3306/' .env
          sed -i 's/DB_DATABASE=lara_ecommerce_api/DB_DATABASE=lara_ecommerce_api/' .env
          sed -i 's/DB_USERNAME=root/DB_USERNAME=root/' .env
          sed -i 's/DB_PASSWORD=/DB_PASSWORD=password/' .env

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h127.0.0.1 -P3306 --silent; do
            echo 'Waiting for MySQL to be ready...'
            sleep 5
          done

      - name: Generate application key
        run: php artisan key:generate

      - name: Run migrations
        run: php artisan migrate --no-interaction --env=testing

      - name: Seed database
        run: php artisan db:seed --no-interaction --env=testing

      - name: Run test suite
        run: php artisan test --env=testing

      - name: Generate test coverage report
        run: |
          mkdir -p test-coverage
          php artisan test --coverage-html test-coverage

      - name: Upload test coverage report
        uses: actions/upload-artifact@v2
        with:
          name: test-coverage
          path: test-coverage
