name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: lara_ecommerce_api
        ports:
          - 3307:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose -y

      - name: Build Docker images
        run: docker-compose -f docker-compose.yml build

      - name: Start Docker containers
        run: docker-compose -f docker-compose.yml up -d

      - name: Wait for MySQL
        run: |
          while ! docker-compose exec db mysqladmin ping -h"db" --silent; do
            echo 'Waiting for MySQL to be ready...'
            sleep 5
          done
        shell: bash

      - name: Install dependencies
        run: docker-compose run --rm app composer install --no-interaction --prefer-dist

      - name: Copy .env file
        run: docker-compose run --rm app cp .env.example .env

      - name: Update .env for testing
        run: |
          docker-compose run --rm app sh -c "sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=mysql/' .env"
          docker-compose run --rm app sh -c "sed -i 's/DB_HOST=127.0.0.1/DB_HOST=db/' .env"
          docker-compose run --rm app sh -c "sed -i 's/DB_PORT=3306/DB_PORT=3306/' .env"
          docker-compose run --rm app sh -c "sed -i 's/DB_DATABASE=lara_ecommerce_api/DB_DATABASE=lara_ecommerce_api/' .env"
          docker-compose run --rm app sh -c "sed -i 's/DB_USERNAME=root/DB_USERNAME=root/' .env"
          docker-compose run --rm app sh -c "sed -i 's/DB_PASSWORD=/DB_PASSWORD=password/' .env"

      - name: Generate application key
        run: docker-compose run --rm app php artisan key:generate

      - name: Run migrations
        run: docker-compose run --rm app php artisan migrate --no-interaction --env=testing

      - name: Seed database
        run: docker-compose run --rm app php artisan db:seed --no-interaction --env=testing

      - name: Run test suite
        run: docker-compose run --rm app php artisan test --env=testing

      - name: Generate test coverage report
        run: |
          mkdir -p test-coverage
          docker-compose run --rm app php artisan test --coverage-html test-coverage

      - name: Upload test coverage report
        uses: actions/upload-artifact@v2
        with:
          name: test-coverage
          path: test-coverage
